# Travis CI integration
# Defaults to GNU GCC and autotools: ./configure && make && make test
language: c

# We don't need to install packages, use dockerized build, quicker
sudo: false

# Test build with both GCC and Clang (LLVM)
compiler:
  - gcc
  - clang

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   # via the "travis encrypt" command using the project repo's public key
   - secure: "I+tezyVxzs59eMMSanZwwbnfCF5Eg3bNpoUbl9jC/9TQKYJt/BpBB14YEVyZ6UfP8uImZ71YUbJuLSm/shtPvZActKu325lxMVPerGJsTRvjqxVI90QsPBtSXIKLX/GcfS+7aRJSoQG8NWtyObfUYVBSWbLIxDZddmMQSCHiSy0="

before_install:
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  apt:
    packages:
      - tree
      - bats
  coverity_scan:
    project:
      name: "troglobit/netcalc"
      description: "Simplified clone of sipcalc with ipcalc looks"
    notification_email: troglobit@gmail.com
    build_command_prepend: ./autogen.sh && ./configure
    build_command: make -j5 clean all
    branch_pattern: dev

# We don't store generated files (configure and Makefile) in GIT,
# so we must customize the default build script to run ./autogen.sh
script:
  - ./autogen.sh
  - ./configure --prefix= --disable-ipcalc-symlink
  - make clean
  - make V=1
  - DESTDIR=~/tmp make install-strip
  - tree ~/tmp
  - ldd ~/tmp/bin/netcalc
  - size ~/tmp/bin/netcalc
  - make check
