# Travis CI integration
# Defaults to GNU GCC and autotools: ./configure && make && make test
language: c

# We don't need to install packages, use dockerized build, quicker
sudo: false

# Test build with both GCC and Clang (LLVM)
compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - tree
      - bats

# We don't store generated files (configure and Makefile) in GIT,
# so we must customize the default build script to run ./autogen.sh
script:
  - ./autogen.sh
  - ./configure --prefix=
  - make clean
  - make V=1
  - DESTDIR=~/tmp make install-strip
  - tree ~/tmp
  - ldd ~/tmp/bin/netcalc
  - size ~/tmp/bin/netcalc
  - make check
